### ISSUE TITLE
onedatify upgrade does not print message on success

### ISSUE THREAD

**Issue by tkotisis** [onedata/onedata#24]
On the contrary, an error message is printed to stdout:
> onedatify upgrade --version "18.02.0-rc10" -s
> sed: can't read : No such file or directory

Although the upgrade seems to succeed, an unsuspecting user would assume the opposite.

**Comment by groundnuty** [comment]
in rc13 this issue has been fixed.

**Comment by tkotisis** [comment]
@groundnuty the message still appears when upgrading from rc10 to rc13.
So i guess you mean it won't happen when upgrading rc13.
