### ISSUE TITLE
Invalid email format when using onedatify

### ISSUE THREAD

**Issue by gmolto** [onedata/onedata#32]
Hi,

Attempting to install a Oneprovider using the onedatify script from the EGI Data Hub triggers a command-line wizard. When asked to enter an e-mail address, indicating an e-mail address with a subdomain (such as user@sub.domain.com) is considered an invalid e-mail format. Using user@domain.com is accepted.

**Comment by groundnuty** [comment]
I've fixed it. It will be included in the next release.

**Comment by alfonpd** [comment]
Bug still present. When I use a email with characters like "-", the validation script reports bad email format.

########## Basic parameters ###########
Please enter the preety name of your oneprovider (default: oneprovider-01.localhost):
Enter a new administration password for the Oneprovider or the password will be autogenerated: XXXXXXXX
Your new password to login into Oneprovider is: XXXXXXXXXX
Please enter the email address that will be used as the emergency contact for this provider (default: ): mymail@one-two.org
Invalid email format. The email must match: [a-zA-Z0-9]+(.[a-zA-Z0-9]+)*@[a-zA-Z0-9]+(.[a-zA-Z0-9]+)+
Please enter the email address that will be used as the emergency contact for this provider (default: ):

**Comment by lopiola** [comment]
This issue is tracked in #44
